add_newline = false
format = """\
  $python\
  $rust\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $character\
"""

[git_branch]
format = " [$symbol$branch(:$remote_branch)]($style)"

